### PR TITLE
Update to React 17, Babel 7, material-ui 5, Storybook 6 and other deps

### LINKED ISSUE #32: Support React 17
I need `segmented-control` to work with a React 17 project of mine.

I tried updating the dependencies myself but hit a roadblock as `formsy-react` [still requires React 16](https://github.com/formsy/formsy-react/issues/583), partly because `airbnb-prop-types` [still requires React 16](https://github.com/airbnb/prop-types/pull/74).

Filing this issue to track the progress of `formsy-react`'s support for React 17. Once this is done, I'll submit a PR if I have time to finalize the work I've done.

### PR DESCRIPTION
**Pull request by loan-laux**
Fixes #32 

As the title says, this updates `segmented-control` to support React 17. While I was in there, I also updated Babel to version 7, `material-ui` to version 5, `storybook` to version 6 and other misc dependencies that were outdated.

### CODE REVIEW

**Comment by loan-laux** [comment]
I've just realized that I deleted the `package-lock.json` file. I thought that I had mistakenly did an `npm install` on my local version, so I deleted it before pushing. Is it on purpose that we have both a `package-lock.json` and a `yarn.lock`?

**Comment by loan-laux** [comment]
@lorensr I've assumed that `package-lock.json` and `yarn.lock` were cohabiting for a reason, so I've put `package-lock.json` back into place. Let me know if you have any feedback on the PR!

**Comment by lorensr** [comment]
Looks like you added yarn in 2018 😄

https://github.com/lorensr/segmented-control/commits/master/yarn.lock

Published `0.1.13`, thanks for the update!

**Comment by loan-laux** [comment]
Oh well. I can't remember why I did that.

r_811491_uTXmv

Thanks for merging though, @lorensr!

**Pull request merged**
