### PR TITLE
add @babel/plugin-transform-runtime and update build script

### LINKED ISSUE #37: Production build is broken
In my last PR, I updated Babel but forgot to update the `prepublish.sh` script. This causes JavaScript files not to be compiled, leaving you with only the stylesheet in the `dist` directory.

### PR DESCRIPTION
**Pull request by loan-laux**
Signed-off-by: Loan Laux <loan@outgrow.io>

Resolves #37 

The production build script is currently broken because I hadn't updated `prepublish.sh` for Babel 7. This PR fixes that, and makes `prepublish.sh` work again.

### CODE REVIEW

**Comment by lorensr** [comment]
Thanks, published ☺️

**Comment by loan-laux** [comment]
Thanks @lorensr! Was it published to NPM?

**Comment by lorensr** [comment]
Yep

**Comment by loan-laux** [comment]
Strange, I installed version `0.1.14` on my project, but I still don't have any JS files in the `dist` directory. When I do `npm run prepublishOnly` on my local copy of `segmented-control`, it does build correctly though.

Screen Shot 2021-01-21 at 11 59 12

@lorensr, sorry to bug you with this, but did you `npm install` before running the script to make sure you have `@babel/plugin-transform-runtime`? Did `prepublish.sh` throw any error?

**Comment by lorensr** [comment]
Oops! How's 0.1.15?

**Comment by PierrotGIT** [comment]
FYI same issue for me, 0.1.15 fixed the issue ;)

**Comment by loan-laux** [comment]
@lorensr @PierrotGIT I can confirm as well that `0.1.15` fixed the issue. Thanks!

**Pull request merged**
